import tseslint from 'typescript-eslint';
import unusedImports from 'eslint-plugin-unused-imports';
import reactHooks from 'eslint-plugin-react-hooks';
import nextPlugin from '@next/eslint-plugin-next';
import globals from 'globals';

/**
 * Lean, focused lint config. The single job here is killing dead imports/vars (autofixable) so they
 * never accumulate — not enforcing a full style ruleset. Backend (`src/`) and the web app (`web/`)
 * share it. Run `npm run lint` to check, `npm run lint:fix` to autofix.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/web-dist/**',
      '**/.next/**',
      '**/coverage/**',
      '**/.worktrees/**',
      '**/.artifacts/**',
      '**/benchmark-env/**',
      'web/public/**',
      'web/scripts/**',
      // Bundled plugin browser assets are generated by build:plugins-web; lint their web-src input.
      'plugins/*/web/**',
      // The Playwright E2E harness has its own dedicated tsconfig typecheck; keep it out of the app lint
      // (its fixture `use()` callbacks trip react-hooks/rules-of-hooks). Mirrors the tsc/knip/depcruise
      // exclusions for this tree.
      'web/tests/e2e/**',
      '**/*.tsbuildinfo',
      '**/*.d.ts',
    ],
  },
  {
    // Don't touch inline `eslint-disable` directives for rules this lean config doesn't manage
    // (e.g. `no-constant-condition`) — otherwise `--fix` would strip them and lose the intent.
    linterOptions: { reportUnusedDisableDirectives: 'off' },
  },
  {
    files: ['**/*.{ts,tsx,mts,cts,js,mjs,cjs}'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: { ecmaVersion: 'latest', sourceType: 'module', ecmaFeatures: { jsx: true } },
      globals: { ...globals.node, ...globals.browser },
    },
    plugins: { 'unused-imports': unusedImports },
    rules: {
      // Delegated to unused-imports (it can autofix imports; the base rule can't).
      'no-unused-vars': 'off',
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': ['warn', {
        vars: 'all',
        varsIgnorePattern: '^_',
        args: 'after-used',
        argsIgnorePattern: '^_',
        // A name destructured alongside a `...rest` is the standard "omit this property" idiom
        // (e.g. `const { apiKey, ...safe } = row`) — it exists only to be excluded, so don't flag it.
        ignoreRestSiblings: true,
      }],
    },
  },
  {
    // Type-aware rules, deliberately four of them rather than a strict preset: each one catches a class
    // of real defect (dead branch, lying assertion, unawaited promise, forgotten union member) and none
    // of them is a style opinion. The project service hands every file to the tsconfig that already owns
    // it — `tsconfig.json` for `src/`, `web/tsconfig.json` for the app — so no file is forced into a
    // foreign program. `tests/` is out: it is in no tsconfig today and does not type-check
    // (1000+ errors from partial fixtures and mock doubles), so type information there would be wrong,
    // and a rule that deletes a guard from a lying type is worse than no rule.
    files: ['src/**/*.ts', 'web/**/*.{ts,tsx}'],
    ignores: [
      // Excluded from web/tsconfig.json (it belongs to the Playwright harness), so no project owns it.
      'web/playwright.config.ts',
    ],
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    plugins: { '@typescript-eslint': tseslint.plugin },
    rules: {
      // A switch WITH a default already says what happens to the rest, so only a switch without one has
      // to enumerate its union. That is the half that catches a member added to a union later.
      '@typescript-eslint/switch-exhaustiveness-check': ['error', { considerDefaultExhaustiveForUnions: true }],
    },
  },
  {
    // Enabled in `src/` and not yet in `web/`, where they are still owed real reading: 444 unnecessary
    // assertions (392 of them in `web/tests`, where an `expect(x!)` is harmless) and 83 floating
    // promises, almost all `queryClient.invalidateQueries(...)` — fire-and-forget by TanStack Query's
    // own design, so awaiting them in `onSuccess` would change behavior rather than fix anything.
    files: ['src/**/*.ts'],
    rules: {
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-unnecessary-type-assertion': 'error',
    },
  },
  {
    // no-unnecessary-condition needs a judgement per finding — delete a dead guard, or fix the type that
    // lies about it — so it is widened one directory at a time as those judgements are made. Still owed:
    // src/brain (112), src/api (68), src/cli (64), src/plugins (32) and web (245).
    files: [
      'src/daemon/**/*.ts', 'src/embeddings/**/*.ts', 'src/integrations/**/*.ts',
      'src/privileged/**/*.ts', 'src/shared/**/*.ts', 'src/store/**/*.ts', 'src/subagent/**/*.ts',
    ],
    rules: {
      // `while (true)` is the language's own spelling of an unbounded loop, not a mistaken condition.
      '@typescript-eslint/no-unnecessary-condition': ['error', { allowConstantLoopConditions: 'only-allowed-literals' }],
    },
  },
  {
    // A plugin's browser bundle is React too — the pages extracted out of core web keep their inline
    // hook directives, and hook correctness matters just as much once the code is served from a plugin.
    // Next's plugin is deliberately absent: a bundle has no Next router, pages or <Image>.
    files: ['plugins/*/web-src/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },
  {
    // Web app (Next.js + React): register the react-hooks and Next plugins so the codebase's inline
    // `eslint-disable` directives resolve, and we get hook-correctness + Next best-practice checks.
    files: ['web/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks, '@next/next': nextPlugin },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      // This is a self-hosted standalone app with no image-optimization loader; every image is a
      // fixed local asset (logos, icons) or a user avatar, where `next/image` adds complexity for no
      // benefit. Plain `<img>` is the deliberate, app-wide choice.
      '@next/next/no-img-element': 'off',
      '@next/next/no-html-link-for-pages': 'off',
    },
  },
  {
    // Overlay semantics on native DOM nodes belong to the shadcn/Radix primitive layer. A custom
    // component such as <PopoverContent role="dialog"> is already composing that layer, so the AST
    // selector deliberately targets lowercase host elements only — no source-text regex guessing.
    files: ['web/app/**/*.{ts,tsx}', 'web/components/**/*.{ts,tsx}', 'web/modules/**/*.{ts,tsx}'],
    ignores: [
      'web/components/ui/shadcn/**',
      // The navigation is a column on desktop and a modal sheet on narrow screens. It cannot join the
      // body-portalled overlay stack without making its own shell ancestor inert.
      'web/components/shell/SidebarNav.tsx',
      // Radix has no combobox primitive. The surrounding Dialog is Radix; only its native listbox and
      // option protocol remain application-owned and are tested as one aria-activedescendant widget.
      'web/components/shell/CommandPalette.tsx',
    ],
    rules: {
      'no-restricted-syntax': ['error',
        {
          selector: "JSXOpeningElement[name.type='JSXIdentifier'][name.name=/^[a-z]/] JSXAttribute[name.name='role'] Literal[value=/^(dialog|menu|listbox|tooltip)$/]",
          message: 'Native overlay roles belong in a shadcn/Radix primitive, not an app surface.',
        },
        {
          selector: "JSXOpeningElement[name.type='JSXIdentifier'][name.name=/^[a-z]/] > JSXAttribute[name.name='aria-modal']",
          message: 'aria-modal belongs in a shadcn/Radix primitive, not an app surface.',
        },
      ],
    },
  },
);
