import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { unsupportedRuntime } from './runtimeClient.mjs';

/** The root filesystem this release can build a managed Project environment from, and where its copies live.
 *
 * The machine runtime has no image store and never builds a root filesystem on the host it serves. Producing
 * one means running a package manager against a distribution mirror, so the release pipeline builds one
 * content-addressed archive that every host downloads and verifies by digest. */

export const ARTIFACT_BASE_URL = 'https://github.com/dragocz95/elowen/releases/download';
export const ARTIFACT_MIRROR_SETTING = 'rootfsArtifactBaseUrl';
export const MAX_ARTIFACT_BYTES = 4 * 1024 * 1024 * 1024;

export const ROOTFS_RECIPES = Object.freeze({
  'project-base': Object.freeze({
    version: 1,
    suite: 'bookworm',
    variant: 'important',
    packages: Object.freeze([
      'systemd', 'systemd-sysv', 'dbus', 'ca-certificates', 'curl', 'iproute2', 'procps', 'less',
      'git', 'openssh-client', 'python3', 'bash', 'tar', 'util-linux', 'ripgrep',
      'chromium', 'fonts-liberation', 'poppler-utils',
      'libreoffice-writer', 'libreoffice-calc', 'libreoffice-impress',
    ]),
    node: Object.freeze({ version: '24.8.0' }),
    masked: Object.freeze(['systemd-remount-fs.service', 'getty.target']),
    enabled: Object.freeze(['systemd-networkd.service', 'systemd-networkd.socket']),
    directories: Object.freeze(['/workspace', '/data', '/run/elowen']),
  }),
});

export const PROJECT_ARTIFACT = 'project-base';

/** Pinned copies generated by `scripts/build-rootfs-artifact.mjs`. */
const pinned = JSON.parse(readFileSync(new URL('./rootfsArtifacts.json', import.meta.url), 'utf8'));

export const ROOTFS_ARTIFACTS = Object.freeze(Object.fromEntries(
  Object.entries(pinned.artifacts).map(([reference, { digest, sizeBytes, path }]) => [
    reference, Object.freeze({ digest, sizeBytes, path }),
  ]),
));

const REFERENCE = /^([a-z][a-z0-9-]{0,40})@([1-9][0-9]{0,8})$/;
export const ARTIFACT_DIGEST = /^sha256:[a-f0-9]{64}$/;

export function artifactReference(name) {
  const recipe = Object.hasOwn(ROOTFS_RECIPES, name) ? ROOTFS_RECIPES[name] : null;
  if (!recipe) throw Object.assign(new Error(`Unknown root filesystem recipe: ${name}`), { code: 'artifact_unknown' });
  return `${name}@${recipe.version}`;
}

const LEGACY_IMAGE = /^(localhost|docker\.io|quay\.io|ghcr\.io)\//;

export function isLegacyImageReference(reference) {
  return typeof reference === 'string' && LEGACY_IMAGE.test(reference);
}

export function parseArtifactReference(reference) {
  const match = typeof reference === 'string' ? REFERENCE.exec(reference) : null;
  if (match) return { name: match[1], version: Number(match[2]) };
  if (isLegacyImageReference(reference)) throw unsupportedRuntime();
  throw Object.assign(new Error('Invalid root filesystem artifact reference'), { code: 'artifact_unknown' });
}

export function artifactEntry(reference) {
  parseArtifactReference(reference);
  const entry = Object.hasOwn(ROOTFS_ARTIFACTS, reference) ? ROOTFS_ARTIFACTS[reference] : null;
  return entry ? { reference, ...entry } : null;
}

export const knownReferences = () => Object.keys(ROOTFS_ARTIFACTS);

export function blobName(digest) {
  if (!ARTIFACT_DIGEST.test(digest ?? '')) throw Object.assign(new Error('Invalid artifact digest'), { code: 'artifact_digest_invalid' });
  return `${digest.replace(':', '-')}.tar.gz`;
}

export function recipeDigest(name) {
  const recipe = Object.hasOwn(ROOTFS_RECIPES, name) ? ROOTFS_RECIPES[name] : null;
  if (!recipe) throw Object.assign(new Error(`Unknown root filesystem recipe: ${name}`), { code: 'artifact_unknown' });
  return createHash('sha256').update(JSON.stringify(recipe)).digest('hex');
}
