import { describe, it, expect } from 'vitest';
import { createServer } from '../../src/api/server.js';
import { EventBus } from '../../src/api/sse.js';
import { FakeClock } from '../../src/shared/clock.js';
import { ConfigStore } from '../../src/store/configStore.js';
import { UserStore } from '../../src/store/userStore.js';
import { ProjectStore } from '../../src/store/projectStore.js';
import { UserProjectStore } from '../../src/store/userProjectStore.js';
import { PluginRegistry } from '../../src/plugins/registry.js';
import { PluginRegistryProvider } from '../../src/plugins/pluginsProvider.js';
import { openPluginTablesDb } from '../helpers/pluginTablesDb.js';
import type { CronConversationLink } from '../../src/plugins/api.js';
import type { ConversationJobLink, ConversationLinksResponse } from '../../web/lib/types.js';
import type { ConversationSubagentBranches, ConversationSubagentNode } from '../../src/store/brainDelegationStore.js';

/** GET /brain/conversation-links is the ONE read behind the collapsed scheduled-job branches. It is
 *  organizational navigation and nothing else: it never starts, pauses or reschedules anything, and the
 *  links it hands out are generated by core so a plugin cannot contribute a URL of its own.
 *
 *  Everything it answers is bounded by what the caller may already see — `mine` by the caller's actual
 *  personal conversation list, `all` by the admin register — so a job attached to a conversation outside
 *  that set simply is not in the response. */

type LinksHook = (input: { requesterUserId: number; requesterIsAdmin: boolean; conversationIds: readonly string[] }) => CronConversationLink[];

function setup(opts: {
  /** Absent = no cron control at all (plugin disabled or uninstalled). */
  cron?: 'legacy' | LinksHook;
  mine?: { id: string }[];
  managed?: { id: string }[];
  /** Session rows the run-target resolution may find, keyed by id. Absent = no store at all. */
  rows?: Record<string, { user_id: number }>;
  /** The sub-agent branch the core store answers with, or a thrower to simulate a failed read. */
  branches?: (rootIds: readonly string[]) => ConversationSubagentBranches;
} = {}) {
  const db = openPluginTablesDb(':memory:');
  db.prepare("INSERT INTO projects (id,slug,path) VALUES (1,'elowen','/o')").run();
  const users = new UserStore(db);
  const admin = users.create('admin', 'pw');
  const amy = users.create('amy', 'pw');
  const config = new ConfigStore(db);

  // cronjob is a grant-gated plugin, so an ordinary account reaches it only once an admin hands it out.
  users.setGrantedPlugins(amy.id, ['cronjob']);

  const calls: { requesterUserId: number; requesterIsAdmin: boolean; conversationIds: readonly string[] }[] = [];
  const branchCalls: string[][] = [];
  let plugins: PluginRegistryProvider | undefined;
  if (opts.cron) {
    const reg = new PluginRegistry();
    reg.userGrantable.add('cronjob');
    const wakeups = { retainedSessionIds: () => [] };
    reg.contextFor('cronjob', {}, { info() {}, warn() {}, error() {} }).registerControl(
      'cron',
      opts.cron === 'legacy' ? wakeups : {
        ...wakeups,
        conversationLinks: (input: { requesterUserId: number; requesterIsAdmin: boolean; conversationIds: readonly string[] }) => {
          calls.push(input);
          return (opts.cron as LinksHook)(input);
        },
      },
    );
    plugins = new PluginRegistryProvider(async () => reg);
  }

  const brain = {
    listSessions: () => opts.mine ?? [],
    listManagedSessions: () => opts.managed ?? [],
  };
  const app = createServer({
    bus: new EventBus(),
    engine: null as never, spawn: null as never, tmux: null as never,
    project: { id: 1, path: '/o' }, fallback: { program: 'claude-code', model: 'sonnet' },
    clock: new FakeClock(0), config, users, projects: new ProjectStore(db), userProjects: new UserProjectStore(db),
    brain: brain as never, plugins,
    ...(opts.rows || opts.branches ? {
      brainStore: {
        getSession: (id: string) => opts.rows?.[id],
        conversationSubagentBranches: (rootIds: readonly string[]) => {
          branchCalls.push([...rootIds]);
          return opts.branches ? opts.branches(rootIds) : { byConversation: {}, truncated: false };
        },
      } as never,
    } : {}),
  });
  return { app, users, admin, amy, calls, branchCalls, adminTok: users.issueToken(admin.id), amyTok: users.issueToken(amy.id) };
}

const node = (over: Partial<ConversationSubagentNode> = {}): ConversationSubagentNode => ({
  kind: 'delegate', key: 'sub:brain-ch-subagent-sub-a', name: 'Audit auth', status: 'done',
  childSessionId: 'brain-ch-subagent-sub-a', children: [], ...over,
});

const auth = (t: string) => ({ headers: { authorization: `Bearer ${t}` } });
const link = (over: Partial<CronConversationLink> = {}): CronConversationLink => ({
  jobId: 'job-1', conversationId: 'brain-2', name: 'Daily digest', enabled: true, ownerUserId: 2, ...over,
});

/** What the response carries when no core store is wired at all — there is nothing to read, which is not
 *  the same answer as "this conversation delegated nothing". */
const NO_BRANCH = { subagentStatus: 'unavailable' as const, subagents: {} };

async function links(
  app: { request: (p: string, o?: unknown) => Promise<Response> },
  token: string,
  scope?: string,
  ids?: string,
) {
  const query = new URLSearchParams();
  if (scope) query.set('scope', scope);
  if (ids !== undefined) query.set('ids', ids);
  const suffix = query.toString();
  const res = await app.request(`/brain/conversation-links${suffix ? `?${suffix}` : ''}`, auth(token));
  return { status: res.status, body: await res.json() as ConversationLinksResponse };
}

describe('GET /brain/conversation-links', () => {
  it('returns the caller\'s own jobs with a core-generated deep link', async () => {
    const { app, amyTok } = setup({ cron: () => [link()], mine: [{ id: 'brain-2' }] });

    const { status, body } = await links(app, amyTok);
    const expected: ConversationJobLink = {
      jobId: 'job-1', conversationId: 'brain-2', name: 'Daily digest', enabled: true,
      scope: 'personal', href: '/p/cronjob?job=job-1', run: null,
    };

    expect(status).toBe(200);
    expect(body).toEqual({ status: 'available', links: [expected], ...NO_BRANCH });
  });

  it('passes the caller\'s ACTUAL personal conversation list as the authorized set', async () => {
    const { app, amyTok, calls } = setup({ cron: () => [], mine: [{ id: 'brain-2' }, { id: 'brain-2-b' }] });

    await links(app, amyTok);

    expect(calls).toEqual([{ requesterUserId: 2, requesterIsAdmin: false, conversationIds: ['brain-2', 'brain-2-b'] }]);
  });

  /** The plugin is not trusted to have filtered correctly: a link naming a conversation outside the
   *  authorized set would otherwise announce that a conversation exists, and put a job branch on a row
   *  the caller never asked about. */
  it('drops a link whose conversation is not in the authorized set', async () => {
    const { app, amyTok } = setup({
      cron: () => [link(), link({ jobId: 'job-2', conversationId: 'brain-99' })],
      mine: [{ id: 'brain-2' }],
    });

    const { body } = await links(app, amyTok);

    expect(body.links.map((l) => l.jobId)).toEqual(['job-1']);
  });

  /** An instance job may be attached to an ordinary account's conversation. Its name is instance
   *  configuration, so only an administrator sees it. */
  it('hides a foreign and an instance job from an ordinary caller but shows both to an admin', async () => {
    const all = () => [
      link({ jobId: 'own', ownerUserId: 2 }),
      link({ jobId: 'foreign', ownerUserId: 1 }),
      link({ jobId: 'instance', ownerUserId: null }),
    ];
    const mine = [{ id: 'brain-2' }];

    const ordinary = setup({ cron: all, mine });
    expect((await links(ordinary.app, ordinary.amyTok)).body.links.map((l) => l.jobId)).toEqual(['own']);

    const asAdmin = setup({ cron: all, mine });
    const body = (await links(asAdmin.app, asAdmin.adminTok)).body;
    expect(body.links.map((l) => l.jobId)).toEqual(['own', 'foreign', 'instance']);
    expect(body.links.map((l) => l.scope)).toEqual(['personal', 'personal', 'instance']);
  });

  it('serves scope=all from the admin register and refuses it to a non-admin', async () => {
    const { app, adminTok, amyTok, calls } = setup({
      cron: () => [link({ conversationId: 'brain-7' })],
      mine: [{ id: 'brain-2' }],
      managed: [{ id: 'brain-7' }],
    });

    const admin = await links(app, adminTok, 'all');
    expect(admin.body.links.map((l) => l.conversationId)).toEqual(['brain-7']);
    expect(calls[0]).toEqual({ requesterUserId: 1, requesterIsAdmin: true, conversationIds: ['brain-7'] });

    const refused = await links(app, amyTok, 'all');
    expect(refused.status).toBe(403);
  });

  it('reports unavailable — never an empty job list — when the plugin is absent', async () => {
    const { app, amyTok } = setup({ mine: [{ id: 'brain-2' }] });

    expect((await links(app, amyTok)).body).toEqual({ status: 'unavailable', links: [], ...NO_BRANCH });
  });

  /** An older installed cronjob plugin registers the control WITHOUT the navigation method. It must keep
   *  resolving as the cron control (pending wake-ups stay protected) while the branch simply does not
   *  appear. */
  it('reports unavailable for an older plugin whose control has no conversationLinks method', async () => {
    const { app, amyTok } = setup({ cron: 'legacy', mine: [{ id: 'brain-2' }] });

    expect((await links(app, amyTok)).body).toEqual({ status: 'unavailable', links: [], ...NO_BRANCH });
  });

  it('reports an error rather than a confirmed empty list when the plugin read fails', async () => {
    const { app, amyTok } = setup({
      cron: () => { throw new Error('jobs.json unreadable'); },
      mine: [{ id: 'brain-2' }],
    });

    const { status, body } = await links(app, amyTok);

    expect(status).toBe(200);
    expect(body).toEqual({ status: 'error', links: [], ...NO_BRANCH });
  });

  it('reports unavailable when the caller\'s plugin grant is revoked', async () => {
    const { app, users, amy, amyTok } = setup({ cron: () => [link()], mine: [{ id: 'brain-2' }] });

    users.setGrantedPlugins(amy.id, []);

    expect((await links(app, amyTok)).body).toEqual({ status: 'unavailable', links: [], ...NO_BRANCH });
  });

  /** The link is built by core from the job id alone, so a plugin cannot point a navigation row at an
   *  arbitrary destination, and a malformed contribution is dropped instead of rendered. */
  it('ignores a plugin-supplied url and drops malformed entries', async () => {
    const { app, amyTok } = setup({
      cron: () => ([
        { ...link({ jobId: 'a b/c?d' }), href: 'https://evil.example/steal', url: 'https://evil.example/steal' },
        { ...link({ jobId: '' }) },
        { ...link({ jobId: 'blank-name', name: '   ' }) },
        { ...link({ jobId: 'bad-id' }), conversationId: 42 },
      ] as unknown as CronConversationLink[]),
      mine: [{ id: 'brain-2' }],
    });

    const { body } = await links(app, amyTok);

    expect(body.links).toEqual([{
      jobId: 'a b/c?d', conversationId: 'brain-2', name: 'Daily digest', enabled: true,
      scope: 'personal', href: `/p/cronjob?job=${encodeURIComponent('a b/c?d')}`, run: null,
    }]);
  });

  /** WHERE A JOB RUNS is the plugin's to know and core's to authorize. A named conversation must be the
   *  caller's own real conversation; a cron channel is built by core from the channel id, so a plugin can
   *  never hand back a ready-made session id and point a row at somebody else's transcript. */
  it('resolves a run target the caller may read, and refuses one they may not', async () => {
    const { app, amyTok } = setup({
      cron: () => ([
        { ...link({ jobId: 'own' }), runSessionId: 'brain-2' },
        { ...link({ jobId: 'channel' }), runChannelId: 'job-channel' },
        { ...link({ jobId: 'foreign' }), runSessionId: 'brain-1' },
        { ...link({ jobId: 'gone' }), runSessionId: 'brain-404' },
        { ...link({ jobId: 'smuggled' }), runSessionId: 'brain-ch-discord-42' },
      ] as unknown as CronConversationLink[]),
      mine: [{ id: 'brain-2' }],
      rows: {
        'brain-2': { user_id: 2 },
        'brain-1': { user_id: 1 },
        'brain-ch-cron-job-channel': { user_id: 2 },
        'brain-ch-discord-42': { user_id: 2 },
      },
    });

    const { body } = await links(app, amyTok);

    expect(body.links.map((l) => [l.jobId, l.run])).toEqual([
      ['own', { sessionId: 'brain-2', continuable: true }],
      ['channel', { sessionId: 'brain-ch-cron-job-channel', continuable: false }],
      // Somebody else's conversation, a row that does not exist, and a channel session smuggled in as a
      // conversation id all resolve to nothing at all.
      ['foreign', null],
      ['gone', null],
      ['smuggled', null],
    ]);
  });

  it('needs authentication', async () => {
    const { app } = setup({ cron: () => [link()], mine: [{ id: 'brain-2' }] });

    expect((await app.request('/brain/conversation-links')).status).toBe(401);
  });
});

/** The same read also carries the CORE sub-agent branch — the delegations and workflows that ran under
 *  each conversation. It is core data rather than a plugin contribution, which is why it survives
 *  everything the cron half can do wrong, and why its roots are the authorized listing and nothing else. */
describe('GET /brain/conversation-links — sub-agent branches', () => {
  it('answers for the caller\'s own conversations beside the scheduled jobs', async () => {
    const { app, amyTok, branchCalls } = setup({
      cron: () => [link()],
      mine: [{ id: 'brain-2' }, { id: 'brain-2-b' }],
      branches: () => ({ byConversation: { 'brain-2': [node()] }, truncated: false }),
    });

    const { body } = await links(app, amyTok);

    expect(branchCalls).toEqual([['brain-2', 'brain-2-b']]);
    expect(body.subagentStatus).toBe('available');
    expect(body.subagents).toEqual({ 'brain-2': [node()] });
    // The scheduled-job half is untouched by any of it.
    expect(body.status).toBe('available');
    expect(body.links.map((l) => l.jobId)).toEqual(['job-1']);
  });

  /** The cron plugin can be missing, ungranted or broken. None of those is a statement about the
   *  sub-agents a conversation ran, so none of them may blank that branch. */
  it('keeps the sub-agent branch when the cron read fails outright', async () => {
    const { app, amyTok } = setup({
      cron: () => { throw new Error('jobs.json unreadable'); },
      mine: [{ id: 'brain-2' }],
      branches: () => ({ byConversation: { 'brain-2': [node()] }, truncated: false }),
    });

    const { body } = await links(app, amyTok);

    expect(body.status).toBe('error');
    expect(body.links).toEqual([]);
    expect(body.subagentStatus).toBe('available');
    expect(body.subagents).toEqual({ 'brain-2': [node()] });
  });

  it('keeps the sub-agent branch when the cron plugin is absent altogether', async () => {
    const { app, amyTok } = setup({
      mine: [{ id: 'brain-2' }],
      branches: () => ({ byConversation: { 'brain-2': [node()] }, truncated: false }),
    });

    const { body } = await links(app, amyTok);

    expect(body.status).toBe('unavailable');
    expect(body.subagents).toEqual({ 'brain-2': [node()] });
  });

  /** A failed core read is reported as a failure. Answering `available` with an empty map would tell the
   *  reader that these conversations delegated nothing, which is a wrong answer rather than an empty one. */
  it('reports an error rather than a confirmed empty branch when the store read fails', async () => {
    const { app, amyTok } = setup({
      cron: () => [link()],
      mine: [{ id: 'brain-2' }],
      branches: () => { throw new Error('database is locked'); },
    });

    const { status, body } = await links(app, amyTok);

    expect(status).toBe(200);
    expect(body.subagentStatus).toBe('error');
    expect(body.subagents).toEqual({});
    // The jobs still came back — one half failing does not cancel the other.
    expect(body.links.map((l) => l.jobId)).toEqual(['job-1']);
  });

  /** `?ids` narrows the answer to the page on screen. It is INTERSECTED with what core authorized, so a
   *  forged id names nothing: the reply cannot be used to discover that a conversation exists. */
  it('intersects explicitly requested roots with the authorized listing', async () => {
    const { app, amyTok, branchCalls } = setup({
      cron: () => [],
      mine: [{ id: 'brain-2' }, { id: 'brain-2-b' }],
      branches: () => ({ byConversation: {}, truncated: false }),
    });

    await links(app, amyTok, undefined, 'brain-2-b,brain-99,brain-ch-discord-42');

    expect(branchCalls).toEqual([['brain-2-b']]);
  });

  it('falls back to the whole authorized listing when no ids are given', async () => {
    const { app, amyTok, branchCalls } = setup({
      cron: () => [],
      mine: [{ id: 'brain-2' }],
      branches: () => ({ byConversation: {}, truncated: false }),
    });

    await links(app, amyTok, undefined, '');

    expect(branchCalls).toEqual([['brain-2']]);
  });

  /** `mine` is the caller's ACTUAL personal list, never every session that happens to share their user
   *  id: a shared room anchored on the operator must not become a root of their personal navigation. */
  it('roots the personal branch in the personal listing and the admin one in the register', async () => {
    const asUser = setup({
      cron: () => [],
      mine: [{ id: 'brain-2' }],
      managed: [{ id: 'brain-ch-discord-42' }],
      branches: () => ({ byConversation: {}, truncated: false }),
    });
    await links(asUser.app, asUser.amyTok);
    expect(asUser.branchCalls).toEqual([['brain-2']]);

    const asAdmin = setup({
      cron: () => [],
      mine: [{ id: 'brain-1' }],
      managed: [{ id: 'brain-ch-discord-42' }],
      branches: () => ({ byConversation: {}, truncated: false }),
    });
    await links(asAdmin.app, asAdmin.adminTok, 'all');
    expect(asAdmin.branchCalls).toEqual([['brain-ch-discord-42']]);
  });

  it('refuses scope=all to a non-admin before reading anything', async () => {
    const { app, amyTok, branchCalls } = setup({
      cron: () => [],
      mine: [{ id: 'brain-2' }],
      managed: [{ id: 'brain-7' }],
      branches: () => ({ byConversation: { 'brain-7': [node()] }, truncated: false }),
    });

    expect((await links(app, amyTok, 'all')).status).toBe(403);
    expect(branchCalls).toEqual([]);
  });

  it('passes the store\'s truncation flag through instead of presenting a clipped tree as whole', async () => {
    const { app, amyTok } = setup({
      cron: () => [],
      mine: [{ id: 'brain-2' }],
      branches: () => ({ byConversation: { 'brain-2': [node({ truncated: true })] }, truncated: true }),
    });

    const { body } = await links(app, amyTok);

    expect(body.subagents['brain-2']![0]!.truncated).toBe(true);
  });
});
