import { describe, it, expect } from 'vitest';
import { createServer } from '../../src/api/server.js';
import { EventBus } from '../../src/api/sse.js';
import { FakeClock } from '../../src/shared/clock.js';
import { ConfigStore } from '../../src/store/configStore.js';
import { UserStore } from '../../src/store/userStore.js';
import { ProjectStore } from '../../src/store/projectStore.js';
import { UserProjectStore } from '../../src/store/userProjectStore.js';
import { PluginRegistry } from '../../src/plugins/registry.js';
import { PluginRegistryProvider } from '../../src/plugins/pluginsProvider.js';
import { openPluginTablesDb } from '../helpers/pluginTablesDb.js';
import type { CronConversationLink } from '../../src/plugins/api.js';
import type { ConversationJobLink, ConversationLinksResponse } from '../../web/lib/types.js';

/** GET /brain/conversation-links is the ONE read behind the collapsed scheduled-job branches. It is
 *  organizational navigation and nothing else: it never starts, pauses or reschedules anything, and the
 *  links it hands out are generated by core so a plugin cannot contribute a URL of its own.
 *
 *  Everything it answers is bounded by what the caller may already see — `mine` by the caller's actual
 *  personal conversation list, `all` by the admin register — so a job attached to a conversation outside
 *  that set simply is not in the response. */

type LinksHook = (input: { requesterUserId: number; requesterIsAdmin: boolean; conversationIds: readonly string[] }) => CronConversationLink[];

function setup(opts: {
  /** Absent = no cron control at all (plugin disabled or uninstalled). */
  cron?: 'legacy' | LinksHook;
  mine?: { id: string }[];
  managed?: { id: string }[];
} = {}) {
  const db = openPluginTablesDb(':memory:');
  db.prepare("INSERT INTO projects (id,slug,path) VALUES (1,'elowen','/o')").run();
  const users = new UserStore(db);
  const admin = users.create('admin', 'pw');
  const amy = users.create('amy', 'pw');
  const config = new ConfigStore(db);

  // cronjob is a grant-gated plugin, so an ordinary account reaches it only once an admin hands it out.
  users.setGrantedPlugins(amy.id, ['cronjob']);

  const calls: { requesterUserId: number; requesterIsAdmin: boolean; conversationIds: readonly string[] }[] = [];
  let plugins: PluginRegistryProvider | undefined;
  if (opts.cron) {
    const reg = new PluginRegistry();
    reg.userGrantable.add('cronjob');
    const wakeups = { pendingWakeupOriginSessionIds: () => [] };
    reg.contextFor('cronjob', {}, { info() {}, warn() {}, error() {} }).registerControl(
      'cron',
      opts.cron === 'legacy' ? wakeups : {
        ...wakeups,
        conversationLinks: (input: { requesterUserId: number; requesterIsAdmin: boolean; conversationIds: readonly string[] }) => {
          calls.push(input);
          return (opts.cron as LinksHook)(input);
        },
      },
    );
    plugins = new PluginRegistryProvider(async () => reg);
  }

  const brain = {
    listSessions: () => opts.mine ?? [],
    listManagedSessions: () => opts.managed ?? [],
  };
  const app = createServer({
    bus: new EventBus(),
    engine: null as never, spawn: null as never, tmux: null as never,
    project: { id: 1, path: '/o' }, fallback: { program: 'claude-code', model: 'sonnet' },
    clock: new FakeClock(0), config, users, projects: new ProjectStore(db), userProjects: new UserProjectStore(db),
    brain: brain as never, plugins,
  });
  return { app, users, admin, amy, calls, adminTok: users.issueToken(admin.id), amyTok: users.issueToken(amy.id) };
}

const auth = (t: string) => ({ headers: { authorization: `Bearer ${t}` } });
const link = (over: Partial<CronConversationLink> = {}): CronConversationLink => ({
  jobId: 'job-1', conversationId: 'brain-2', name: 'Daily digest', enabled: true, ownerUserId: 2, ...over,
});

async function links(app: { request: (p: string, o?: unknown) => Promise<Response> }, token: string, scope?: string) {
  const res = await app.request(`/brain/conversation-links${scope ? `?scope=${scope}` : ''}`, auth(token));
  return { status: res.status, body: await res.json() as ConversationLinksResponse };
}

describe('GET /brain/conversation-links', () => {
  it('returns the caller\'s own jobs with a core-generated deep link', async () => {
    const { app, amyTok } = setup({ cron: () => [link()], mine: [{ id: 'brain-2' }] });

    const { status, body } = await links(app, amyTok);
    const expected: ConversationJobLink = {
      jobId: 'job-1', conversationId: 'brain-2', name: 'Daily digest', enabled: true,
      scope: 'personal', href: '/p/cronjob?job=job-1',
    };

    expect(status).toBe(200);
    expect(body).toEqual({ status: 'available', links: [expected] });
  });

  it('passes the caller\'s ACTUAL personal conversation list as the authorized set', async () => {
    const { app, amyTok, calls } = setup({ cron: () => [], mine: [{ id: 'brain-2' }, { id: 'brain-2-b' }] });

    await links(app, amyTok);

    expect(calls).toEqual([{ requesterUserId: 2, requesterIsAdmin: false, conversationIds: ['brain-2', 'brain-2-b'] }]);
  });

  /** The plugin is not trusted to have filtered correctly: a link naming a conversation outside the
   *  authorized set would otherwise announce that a conversation exists, and put a job branch on a row
   *  the caller never asked about. */
  it('drops a link whose conversation is not in the authorized set', async () => {
    const { app, amyTok } = setup({
      cron: () => [link(), link({ jobId: 'job-2', conversationId: 'brain-99' })],
      mine: [{ id: 'brain-2' }],
    });

    const { body } = await links(app, amyTok);

    expect(body.links.map((l) => l.jobId)).toEqual(['job-1']);
  });

  /** An instance job may be attached to an ordinary account's conversation. Its name is instance
   *  configuration, so only an administrator sees it. */
  it('hides a foreign and an instance job from an ordinary caller but shows both to an admin', async () => {
    const all = () => [
      link({ jobId: 'own', ownerUserId: 2 }),
      link({ jobId: 'foreign', ownerUserId: 1 }),
      link({ jobId: 'instance', ownerUserId: null }),
    ];
    const mine = [{ id: 'brain-2' }];

    const ordinary = setup({ cron: all, mine });
    expect((await links(ordinary.app, ordinary.amyTok)).body.links.map((l) => l.jobId)).toEqual(['own']);

    const asAdmin = setup({ cron: all, mine });
    const body = (await links(asAdmin.app, asAdmin.adminTok)).body;
    expect(body.links.map((l) => l.jobId)).toEqual(['own', 'foreign', 'instance']);
    expect(body.links.map((l) => l.scope)).toEqual(['personal', 'personal', 'instance']);
  });

  it('serves scope=all from the admin register and refuses it to a non-admin', async () => {
    const { app, adminTok, amyTok, calls } = setup({
      cron: () => [link({ conversationId: 'brain-7' })],
      mine: [{ id: 'brain-2' }],
      managed: [{ id: 'brain-7' }],
    });

    const admin = await links(app, adminTok, 'all');
    expect(admin.body.links.map((l) => l.conversationId)).toEqual(['brain-7']);
    expect(calls[0]).toEqual({ requesterUserId: 1, requesterIsAdmin: true, conversationIds: ['brain-7'] });

    const refused = await links(app, amyTok, 'all');
    expect(refused.status).toBe(403);
  });

  it('reports unavailable — never an empty job list — when the plugin is absent', async () => {
    const { app, amyTok } = setup({ mine: [{ id: 'brain-2' }] });

    expect((await links(app, amyTok)).body).toEqual({ status: 'unavailable', links: [] });
  });

  /** An older installed cronjob plugin registers the control WITHOUT the navigation method. It must keep
   *  resolving as the cron control (pending wake-ups stay protected) while the branch simply does not
   *  appear. */
  it('reports unavailable for an older plugin whose control has no conversationLinks method', async () => {
    const { app, amyTok } = setup({ cron: 'legacy', mine: [{ id: 'brain-2' }] });

    expect((await links(app, amyTok)).body).toEqual({ status: 'unavailable', links: [] });
  });

  it('reports an error rather than a confirmed empty list when the plugin read fails', async () => {
    const { app, amyTok } = setup({
      cron: () => { throw new Error('jobs.json unreadable'); },
      mine: [{ id: 'brain-2' }],
    });

    const { status, body } = await links(app, amyTok);

    expect(status).toBe(200);
    expect(body).toEqual({ status: 'error', links: [] });
  });

  it('reports unavailable when the caller\'s plugin grant is revoked', async () => {
    const { app, users, amy, amyTok } = setup({ cron: () => [link()], mine: [{ id: 'brain-2' }] });

    users.setGrantedPlugins(amy.id, []);

    expect((await links(app, amyTok)).body).toEqual({ status: 'unavailable', links: [] });
  });

  /** The link is built by core from the job id alone, so a plugin cannot point a navigation row at an
   *  arbitrary destination, and a malformed contribution is dropped instead of rendered. */
  it('ignores a plugin-supplied url and drops malformed entries', async () => {
    const { app, amyTok } = setup({
      cron: () => ([
        { ...link({ jobId: 'a b/c?d' }), href: 'https://evil.example/steal', url: 'https://evil.example/steal' },
        { ...link({ jobId: '' }) },
        { ...link({ jobId: 'blank-name', name: '   ' }) },
        { ...link({ jobId: 'bad-id' }), conversationId: 42 },
      ] as unknown as CronConversationLink[]),
      mine: [{ id: 'brain-2' }],
    });

    const { body } = await links(app, amyTok);

    expect(body.links).toEqual([{
      jobId: 'a b/c?d', conversationId: 'brain-2', name: 'Daily digest', enabled: true,
      scope: 'personal', href: `/p/cronjob?job=${encodeURIComponent('a b/c?d')}`,
    }]);
  });

  it('needs authentication', async () => {
    const { app } = setup({ cron: () => [link()], mine: [{ id: 'brain-2' }] });

    expect((await app.request('/brain/conversation-links')).status).toBe(401);
  });
});
