import type { Locale } from '../../lib/i18n';

const en = {
  inspectGit: 'Inspect repository', managed: 'Managed environment', host: 'Host directory', executionKind: 'Execution target',
  privateHint: 'This project is private until deliberately shared. Administrators retain access. Its environment starts only on first use.',
  defaultProject: 'Open default project', defaultHint: 'Every account has a private default project. Opening it does not start its environment.',
  createGrant: 'Allow additional projects', shareGrant: 'Allow project invitations', limit: 'Managed project limit',
  limitHint: 'Includes the default project. Administrators bypass these account limits.',
  savePermissions: 'Save project permissions', permissions: 'Project permissions', members: 'Project members', invite: 'Invite member', userId: 'Account ID',
  userIdHint: 'Ask the person for their account ID. The account directory is restricted to administrators.',
  member: 'Account {id}', removeMember: 'Remove member', leave: 'Leave project',
  sharingWarning: 'Every member can access all existing project files, worktrees, guest browser profiles and credentials stored in the environment. Members have equal management and deletion rights. Private conversations, memories and personal integrations are not shared automatically.',
  credentials: 'Personal integration credentials remain account-private outside this environment. Credentials or integration results placed in project files become accessible to every member.',
  revokeWarning: 'Removing membership blocks further access and cancels tracked executions. Project services remain running. Copied credentials and independently created processes cannot be retracted.',
  inviteDenied: 'Inviting members requires an administrator-granted sharing permission.',
  deleting: 'Project deletion requested. Cleanup is pending.',
  deleteWarning: 'Delete this project and its environment, including files, installed packages, HOME and data? Published sites must be transferred or deleted separately. Private conversation history is preserved.',
  hostMode: 'HOST MODE', hostWarning: 'Commands and files will operate directly on the host, outside a managed project environment. Only administrators can select this target.',
  hostConfirm: 'Use host mode', unknownTarget: 'Execution target not selected',
};
const cs: typeof en = {
  inspectGit: 'Prohlédnout repozitář', managed: 'Spravované prostředí', host: 'Adresář hostitele', executionKind: 'Cíl spouštění',
  privateHint: 'Projekt je soukromý, dokud jej výslovně nesdílíte. Správci mají přístup vždy. Prostředí se spustí až při prvním použití.',
  defaultProject: 'Otevřít výchozí projekt', defaultHint: 'Každý účet má soukromý výchozí projekt. Jeho otevření nespouští prostředí.',
  createGrant: 'Povolit další projekty', shareGrant: 'Povolit pozvání do projektů', limit: 'Limit spravovaných projektů',
  limitHint: 'Zahrnuje výchozí projekt. Na správce se tato omezení účtu nevztahují.',
  savePermissions: 'Uložit oprávnění projektů', permissions: 'Oprávnění projektů', members: 'Členové projektu', invite: 'Pozvat člena', userId: 'ID účtu',
  userIdHint: 'Požádejte danou osobu o ID účtu. Seznam účtů je dostupný pouze správcům.',
  member: 'Účet {id}', removeMember: 'Odebrat člena', leave: 'Opustit projekt',
  sharingWarning: 'Každý člen získá přístup ke všem existujícím souborům projektu, pracovním stromům, profilům prohlížeče a přihlašovacím údajům uloženým v prostředí. Členové mají stejná práva ke správě i smazání. Soukromé konverzace, vzpomínky a osobní integrace se automaticky nesdílejí.',
  credentials: 'Přihlašovací údaje osobních integrací zůstávají soukromé mimo prostředí. Údaje nebo výsledky integrací uložené do souborů projektu jsou dostupné všem členům.',
  revokeWarning: 'Odebrání členství zablokuje další přístup a zruší sledované příkazy. Služby projektu zůstanou spuštěné. Zkopírované údaje ani samostatně vytvořené procesy nelze odvolat.',
  inviteDenied: 'Pozvání členů vyžaduje oprávnění ke sdílení udělené správcem.',
  deleting: 'Bylo vyžádáno smazání projektu. Úklid čeká na dokončení.',
  deleteWarning: 'Smazat projekt a jeho prostředí včetně souborů, nainstalovaných balíčků, HOME a dat? Publikované weby je nutné samostatně převést nebo smazat. Soukromá historie konverzací zůstane zachována.',
  hostMode: 'REŽIM HOSTITELE', hostWarning: 'Příkazy a soubory budou pracovat přímo na hostiteli mimo spravované prostředí projektu. Tento cíl mohou zvolit pouze správci.',
  hostConfirm: 'Použít režim hostitele', unknownTarget: 'Cíl spouštění není vybrán',
};
const sk: typeof en = {
  inspectGit: 'Prezrieť repozitár', managed: 'Spravované prostredie', host: 'Adresár hostiteľa', executionKind: 'Cieľ spúšťania',
  privateHint: 'Projekt je súkromný, kým ho výslovne nezdieľate. Správcovia majú prístup vždy. Prostredie sa spustí až pri prvom použití.',
  defaultProject: 'Otvoriť predvolený projekt', defaultHint: 'Každý účet má súkromný predvolený projekt. Jeho otvorenie nespúšťa prostredie.',
  createGrant: 'Povoliť ďalšie projekty', shareGrant: 'Povoliť pozvania do projektov', limit: 'Limit spravovaných projektov',
  limitHint: 'Zahŕňa predvolený projekt. Na správcov sa tieto obmedzenia účtu nevzťahujú.',
  savePermissions: 'Uložiť oprávnenia projektov', permissions: 'Oprávnenia projektov', members: 'Členovia projektu', invite: 'Pozvať člena', userId: 'ID účtu',
  userIdHint: 'Požiadajte danú osobu o ID účtu. Zoznam účtov je dostupný iba správcom.',
  member: 'Účet {id}', removeMember: 'Odobrať člena', leave: 'Opustiť projekt',
  sharingWarning: 'Každý člen získa prístup ku všetkým existujúcim súborom projektu, pracovným stromom, profilom prehliadača a prihlasovacím údajom uloženým v prostredí. Členovia majú rovnaké práva na správu aj vymazanie. Súkromné konverzácie, spomienky a osobné integrácie sa automaticky nezdieľajú.',
  credentials: 'Prihlasovacie údaje osobných integrácií zostávajú súkromné mimo prostredia. Údaje alebo výsledky integrácií uložené do súborov projektu sú dostupné všetkým členom.',
  revokeWarning: 'Odobratie členstva zablokuje ďalší prístup a zruší sledované príkazy. Služby projektu zostanú spustené. Skopírované údaje ani samostatne vytvorené procesy nemožno odvolať.',
  inviteDenied: 'Pozvanie členov vyžaduje oprávnenie na zdieľanie udelené správcom.',
  deleting: 'Bolo vyžiadané vymazanie projektu. Čistenie čaká na dokončenie.',
  deleteWarning: 'Vymazať projekt a jeho prostredie vrátane súborov, nainštalovaných balíkov, HOME a dát? Publikované weby je nutné samostatne previesť alebo vymazať. Súkromná história konverzácií zostane zachovaná.',
  hostMode: 'REŽIM HOSTITEĽA', hostWarning: 'Príkazy a súbory budú pracovať priamo na hostiteľovi mimo spravovaného prostredia projektu. Tento cieľ môžu zvoliť iba správcovia.',
  hostConfirm: 'Použiť režim hostiteľa', unknownTarget: 'Cieľ spúšťania nie je vybraný',
};
export const managedProjectStrings: Record<Locale, typeof en> = { en, cs, sk };
