import type { Locale } from '../../lib/i18n';

const en = {
  gitEnvironmentStopped: 'Repository details become available once the project environment is running.', managed: 'Managed environment', host: 'Host directory', executionKind: 'Execution target',
  privateHint: 'This project is private until deliberately shared. Administrators retain access. Its environment starts only on first use.',
  defaultProject: 'Open default project', defaultHint: 'Every account has a private default project. Opening it does not start its environment.',
  createGrant: 'Allow additional projects', shareGrant: 'Allow project invitations', limit: 'Managed project limit',
  limitHint: 'Includes the default project. Administrators bypass these account limits.',
  permissions: 'Project permissions', members: 'Project members', invite: 'Invite member', userId: 'Account ID',
  userIdHint: 'Ask the person for their account ID. The account directory is restricted to administrators.',
  member: 'Account {id}',
  accessCountMembers: { one: '{n} user has access', few: '{n} users have access', many: '{n} users have access' },
  accountsGroup: 'Accounts',
  iconEnvironmentStopped: 'Project images become available once the project environment is running. Start it from the Environment tab.',
  sharingWarning: 'Every member can access all existing project files, worktrees, guest browser profiles and credentials stored in the environment. Members have equal management and deletion rights. Private conversations, memories and personal integrations are not shared automatically.',
  inviteDenied: 'Inviting members requires an administrator-granted sharing permission.',
  deleting: 'Project deletion requested. Cleanup is pending.',
  deleteWarning: 'Delete this project and its environment, including files, installed packages, HOME and data? Published sites must be transferred or deleted separately. Private conversation history is preserved.',
};
const cs: typeof en = {
  gitEnvironmentStopped: 'Podrobnosti o repozitáři budou dostupné, jakmile poběží prostředí projektu.', managed: 'Spravované prostředí', host: 'Adresář hostitele', executionKind: 'Cíl spouštění',
  privateHint: 'Projekt je soukromý, dokud jej výslovně nesdílíte. Správci mají přístup vždy. Prostředí se spustí až při prvním použití.',
  defaultProject: 'Otevřít výchozí projekt', defaultHint: 'Každý účet má soukromý výchozí projekt. Jeho otevření nespouští prostředí.',
  createGrant: 'Povolit další projekty', shareGrant: 'Povolit pozvání do projektů', limit: 'Limit spravovaných projektů',
  limitHint: 'Zahrnuje výchozí projekt. Na správce se tato omezení účtu nevztahují.',
  permissions: 'Oprávnění projektů', members: 'Členové projektu', invite: 'Pozvat člena', userId: 'ID účtu',
  userIdHint: 'Požádejte danou osobu o ID účtu. Seznam účtů je dostupný pouze správcům.',
  member: 'Účet {id}',
  accessCountMembers: { one: 'Přístup má {n} uživatel', few: 'Přístup mají {n} uživatelé', many: 'Přístup má {n} uživatelů' },
  accountsGroup: 'Účty',
  iconEnvironmentStopped: 'Obrázky projektu budou dostupné, jakmile poběží prostředí projektu. Spustíte jej na kartě Prostředí.',
  sharingWarning: 'Každý člen získá přístup ke všem existujícím souborům projektu, pracovním stromům, profilům prohlížeče a přihlašovacím údajům uloženým v prostředí. Členové mají stejná práva ke správě i smazání. Soukromé konverzace, vzpomínky a osobní integrace se automaticky nesdílejí.',
  inviteDenied: 'Pozvání členů vyžaduje oprávnění ke sdílení udělené správcem.',
  deleting: 'Bylo vyžádáno smazání projektu. Úklid čeká na dokončení.',
  deleteWarning: 'Smazat projekt a jeho prostředí včetně souborů, nainstalovaných balíčků, HOME a dat? Publikované weby je nutné samostatně převést nebo smazat. Soukromá historie konverzací zůstane zachována.',
};
const sk: typeof en = {
  gitEnvironmentStopped: 'Podrobnosti o repozitári budú dostupné, hneď ako pobeží prostredie projektu.', managed: 'Spravované prostredie', host: 'Adresár hostiteľa', executionKind: 'Cieľ spúšťania',
  privateHint: 'Projekt je súkromný, kým ho výslovne nezdieľate. Správcovia majú prístup vždy. Prostredie sa spustí až pri prvom použití.',
  defaultProject: 'Otvoriť predvolený projekt', defaultHint: 'Každý účet má súkromný predvolený projekt. Jeho otvorenie nespúšťa prostredie.',
  createGrant: 'Povoliť ďalšie projekty', shareGrant: 'Povoliť pozvania do projektov', limit: 'Limit spravovaných projektov',
  limitHint: 'Zahŕňa predvolený projekt. Na správcov sa tieto obmedzenia účtu nevzťahujú.',
  permissions: 'Oprávnenia projektov', members: 'Členovia projektu', invite: 'Pozvať člena', userId: 'ID účtu',
  userIdHint: 'Požiadajte danú osobu o ID účtu. Zoznam účtov je dostupný iba správcom.',
  member: 'Účet {id}',
  accessCountMembers: { one: 'Prístup má {n} používateľ', few: 'Prístup majú {n} používatelia', many: 'Prístup má {n} používateľov' },
  accountsGroup: 'Účty',
  iconEnvironmentStopped: 'Obrázky projektu budú dostupné, hneď ako pobeží prostredie projektu. Spustíte ho na karte Prostredie.',
  sharingWarning: 'Každý člen získa prístup ku všetkým existujúcim súborom projektu, pracovným stromom, profilom prehliadača a prihlasovacím údajom uloženým v prostredí. Členovia majú rovnaké práva na správu aj vymazanie. Súkromné konverzácie, spomienky a osobné integrácie sa automaticky nezdieľajú.',
  inviteDenied: 'Pozvanie členov vyžaduje oprávnenie na zdieľanie udelené správcom.',
  deleting: 'Bolo vyžiadané vymazanie projektu. Čistenie čaká na dokončenie.',
  deleteWarning: 'Vymazať projekt a jeho prostredie vrátane súborov, nainštalovaných balíkov, HOME a dát? Publikované weby je nutné samostatne previesť alebo vymazať. Súkromná história konverzácií zostane zachovaná.',
};
export const managedProjectStrings: Record<Locale, typeof en> = { en, cs, sk };
